accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

images/urls.py
from django.urls import path
from images.views import ImageCreateView, ImageListView, ImageUpdateView

urlpatterns = [
    path("create/", ImageCreateView.as_view(), name="create_image"),
    path("mine/", ImageListView.as_view(), name="list_images"),
    path(
        "<int:pk>/complete/", ImageUpdateView.as_view(), name="complete_task"
    ),
]

my_collections/urls.py
from django.views.generic import TemplateView
from django.urls import path
from my_collections.views import (
    CollectionListView,
    CollectionDetailView,
    CollectionCreateView,
)

urlpatterns = [
    path("", CollectionListView.as_view(), name="list_collections"),
    path("<int:pk>/", CollectionDetailView.as_view(), name="show_collection"),
    path("create/", CollectionCreateView.as_view(), name="create_collection"),
    path(
        "about/",
        TemplateView.as_view(template_name="collections/about.html"),
        name="about_page",
    ),
    path(
        "home/",
        TemplateView.as_view(template_name="collections/home.html"),
        name="home",
    ),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("collections/", include("my_collections.urls")),
    path("", RedirectView.as_view(url="collections/home/"), name="home"),
    path("accounts/", include("accounts.urls")),
    path("images/", include("images.urls")),
]

accounts/models.py
# Create your models here.

images/models.py
from django.db import models
from my_collections.models import Collection, User_auth

# Create your models here.


class Image(models.Model):
    title = models.CharField(max_length=200)
    date_taken = models.DateTimeField()
    img_link = models.URLField(max_length=400)
    description = models.TextField()
    collection = models.ForeignKey(
        Collection, related_name="images", on_delete=models.CASCADE
    )
    photographer = models.ForeignKey(
        User_auth, null=True, related_name="images", on_delete=models.SET_NULL
    )

    def __str__(self):
        return self.title

my_collections/models.py
from django.db import models
from django.conf import settings

User_auth = settings.AUTH_USER_MODEL
# Create your models here.


class Collection(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    cover_image = models.URLField(max_length=500)

    def __str__(self):
        return self.title

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid:
            username = request.POST.get("username")
            password = request.POST.get("password1")
            if User.objects.filter(username=username).first():
                messages.error(request, "This username is already taken")
            else:
                user = User.objects.create_user(
                    username=username,
                    password=password,
                )
                user.save()
                login(request, user)
                return redirect("home")

    else:
        form = UserCreationForm(request.POST)
    context = {"form": form}
    return render(request, "registration/signup.html", context)

images/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView
from images.models import Image

# Create your views here.


class ImageCreateView(LoginRequiredMixin, CreateView):
    model = Image
    template_name = "images/create.html"
    fields = [
        "title",
        "date_taken",
        "img_link",
        "description",
        "collection",
        "photographer",
    ]

    def get_success_url(self) -> str:
        return reverse_lazy(
            "show_collection", args=[self.object.collection.id]
        )


class ImageListView(ListView):
    model = Image
    template_name = "images/list.html"

    def get_queryset(self):
        return Image.objects.filter(photographer=self.request.user)


class ImageUpdateView(LoginRequiredMixin, UpdateView):
    model = Image
    template_name = "images/edit.html"
    fields = [
        "title",
        "date_taken",
        "img_link",
        "description",
        "collection",
        "photographer",
    ]

    def get_success_url(self) -> str:
        return reverse_lazy(
            "show_collection", args=[self.object.collection.id]
        )

my_collections/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from my_collections.models import Collection

# Create your views here.


class CollectionListView(ListView):
    template_name = "collections/list.html"
    model = Collection

    # def get_queryset(self):
    #     return Collection.objects.filter(photgrapher=self.request.user)


class CollectionDetailView(DetailView):
    model = Collection
    template_name = "collections/detail.html"

    # def get_queryset(self):
    #     return Collection.objects.filter(photographer=self.request.user)


class CollectionCreateView(LoginRequiredMixin, CreateView):
    model = Collection
    template_name = "collections/create.html"
    fields = [
        "title",
        "description",
        "cover_image",
    ]

    success_url = reverse_lazy("list_collections")

images/templates/images/create.html
{% extends 'base.html' %}

{% block content %}
<div class="image_form">
  <h2>Add an image</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add to collection</button>
  </form>
</div>
{% endblock content %}

images/templates/images/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div>
    <p>
        This will be a list of images
    </p>
</div>

{% endblock content %}

my_collections/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'collections/styles.css' %}">
    <title>Gallery Alpha</title>
</head>

<body class="home_bg">
    <header>
        <div class="header">
        <nav class="navbar">
            <a href="{% url 'home' %}"><h1>Here onward</h1></a>
            <ul class="nav-links">
                {% url 'list_collections' as collections_url %}
                {% url 'about_page' as about_url %}
                {% url 'login' as login_url %}
                {% url 'signup' as signup_url %}
                {% if user.is_authenticated %}
                
                <li class="nav-item"> <a href="{% url 'list_collections' %}" {% if request.path == collections_url %} class="active" {% endif %}>Collections</a></li>
                <li class="nav-item"> <a href="{% url 'about_page' %}" {% if request.path == about_url %} class="active" {% endif %}>About</a></li>
                <li class="nav-item"> <a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li class="nav-item"> <a href="{% url 'list_collections' %}" {% if request.path == collections_url %} class="active" {% endif %}>Collections</a></li>
                <li class="nav-item"> <a href="{% url 'about_page' %}" {% if request.path == about_url %} class="active" {% endif %}>About</a></li>
                <li class="nav-item"> <a href="{% url 'login' %}" {% if request.path == login_url %} class="active" {%endif %}>Login</a></li>
                <li class="nav-item"> <a href="{% url 'signup' %}" {% if request.path == signup_url %} class="active" {%endif %}>Signup</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
    </header>
    <hr>
    <main>
        <div class="page_container">
            {% block content %}
            {% endblock content %}
        </div>
    </main>
</body>
<footer>
    <div>
        <p>
            Thanks for visiting
        </p>
    </div>
</footer>

</html>

my_collections/templates/collections/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="about">
    <p>Hi there!</p>
    <p>Thanks for stopping by and checking out my work.</p>
    <p class="signature">-Jordan</p>
</div>
{% endblock content %}

my_collections/templates/collections/create.html
{% extends 'base.html' %}

{% block content %}
<div class="collection_form">
    <h2>Create a new collection</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Create collection</button>
    </form>
</div>
{% endblock content %}

my_collections/templates/collections/detail.html
{% extends 'base.html' %}
{% load markdownify %}

{% block content %}

<div class="container">
    <div>
        <h2>{{ collection.title }}</h2>
    </div>
    {% if user.is_staff %}
    <p><a href="{% url 'create_image' %}">Add an image</a></p>
    {% endif %}
    <div class="collection_images">
        {% for image in collection.images.all %}
        <div class="image_wrap">
            <img class="images" src="{{ image.img_link }}" alt="another picture">
            <ul class="image_text">
                <li>{{ image.title }}</li>
                <li>{{ image.date_taken }}</li>
                <li>{{ image.description }}</li>
            </ul>
        </div>
        {% endfor %}

    </div>
</div>

{% endblock content %}

my_collections/templates/collections/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="home">
    <p class="quote">You are here to experience life; not to escape from it.</p>
    <p class="author"> -Stuart Wilde</p>
</div>
{% endblock content %}

my_collections/templates/collections/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div>
        {% if user.is_staff %}
            <a href="{% url 'create_collection' %}">Create a New Collection</a>
        {% endif %}
    </div>
    <div class="covers">
        {% for collection in collection_list %}
        <div class="img_wrap">
            <a href="{% url 'show_collection' collection.pk %}"><img class="cover_image "src="{{ collection.cover_image }}"alt="another picture">
                <p class="cover_title">{{ collection.title }}</p>
            </a>
        </div>
        {% endfor %}

    </div>
</div>

{% endblock content %}